apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-react-app
  links:
    - url: http://localhost:30080
      title: My React App
      icon: dashboard
  annotations:
    github.com/project-slug: daniel-wakefield-ro/my-react-app
    backstage.io/techdocs-ref: dir:.
    kubernetes.io/namespace: default
    kubernetes.io/service-name: my-react-app-service
spec:
  type: website
  lifecycle: development
  owner: user:daniel-wakefield-ro
