apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-react-app
  annotations:
    github.com/project-slug: daniel-wakefield-ro/my-react-app
    backstage.io/source-location: url:https://github.com/daniel-wakefield-ro/my-react-app
    backstage.io/view-url: https://github.com/daniel-wakefield-ro/my-react-app
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  lifecycle: development
  owner: user:daniel-wakefield-ro
