apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-react-app
  links:
    - url: http://localhost:30080
      title: My React App
      icon: dashboard
  annotations:
    github.com/project-slug: daniel-wakefield-ro/my-react-app
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-id: my-react-app
    backstage.io/kubernetes-namespace: default
    backstage.io/kubernetes-service-name: my-react-app-service
    backstage.io/kubernetes-label-selector: 'app=my-react-app'
    datadoghq.com/site: datadoghq.com
    datadoghq.com/dashboard-url: https://p.datadoghq.com/sb/embed/30acddb70-d676173a178eab532dbc4abbac7a9112
spec:
  type: website
  lifecycle: development
  owner: user:daniel-wakefield-ro
  dependsOn:
    - component:default/NewNewNodeService
