apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-react-app
  links:
    - url: http://localhost:30080
      title: My React App
      icon: dashboard
  annotations:
    github.com/project-slug: daniel-wakefield-ro/my-react-app
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-id: my-react-app
    backstage.io/kubernetes-namespace: default
    backstage.io/kubernetes-service-name: my-react-app-service
    backstage.io/kubernetes-label-selector: 'app=my-react-app'
    datadoghq.com/site: datadoghq.com
    datadoghq.com/dashboard-url: https://app.datadoghq.com/dashboard/h7t-3ae-8n9/chris-test?fromUser=false&refresh_mode=sliding&from_ts=1745860485002&to_ts=1745864085002&live=true
spec:
  type: website
  lifecycle: development
  owner: user:daniel-wakefield-ro
  dependsOn:
    - component:default/NewNewNodeService
